table DimCurrency
	lineageTag: 81a4e897-0cbc-4a44-aa38-b2e7b2652b36

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: c6ef2215-36b7-4029-a9f5-d09f0d83e8d2
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: 1b207f04-4302-4b4b-9114-4f4016aa2436
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	column CurrencyDescription
		dataType: string
		lineageTag: 36562d26-d3ae-47fc-953d-487f023da1a8
		summarizeBy: none
		sourceColumn: CurrencyDescription

		annotation SummarizationSetBy = Automatic

	partition DimCurrency = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jzivaljevic\OneDrive - ENDAVA\Desktop\KrisPOCversioning\data\DimCurrency.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CurrencyKey", Int64.Type}, {"CurrencyName", type text}, {"CurrencyDescription", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

