table DimDate
	lineageTag: a5292b7f-0271-4254-a5a3-1e2a1d3fe4ff

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: e5d9e0e8-17e9-4544-948a-ec3620f85c13
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CalendarYear
		dataType: int64
		formatString: 0
		lineageTag: d684eaf5-9857-407d-a0dd-5b0e0513ab74
		summarizeBy: none
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarYearLabel
		dataType: string
		lineageTag: c02cdd4e-4874-4513-9cb9-415c94f5badf
		summarizeBy: none
		sourceColumn: CalendarYearLabel

		annotation SummarizationSetBy = Automatic

	column CalendarHalfYearLabel
		dataType: string
		lineageTag: ba7d5b55-80d3-48ee-9768-df7ca64a5966
		summarizeBy: none
		sourceColumn: CalendarHalfYearLabel

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterLabel
		dataType: string
		lineageTag: 36783685-4437-4da6-a3b6-8e32122d0231
		summarizeBy: none
		sourceColumn: CalendarQuarterLabel

		annotation SummarizationSetBy = Automatic

	column CalendarMonthLabel
		dataType: string
		lineageTag: 9b7a02fa-2ab4-4540-b864-d2728819b841
		summarizeBy: none
		sourceColumn: CalendarMonthLabel

		annotation SummarizationSetBy = Automatic

	column CalendarWeekLabel
		dataType: string
		lineageTag: 8021c28e-ef02-4473-917b-f27a19f1fcbb
		summarizeBy: none
		sourceColumn: CalendarWeekLabel

		annotation SummarizationSetBy = Automatic

	column CalendarDayOfWeekLabel
		dataType: string
		lineageTag: 3027eb31-f4bd-4c76-88fd-e3db61237c17
		summarizeBy: none
		sourceColumn: CalendarDayOfWeekLabel

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: a30d0bf3-9c5b-4cc1-a8b5-bf63dc5ffd3e
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearLabel
		dataType: string
		lineageTag: aa2332f7-32bd-42a6-a14f-bd930e5edb03
		summarizeBy: none
		sourceColumn: FiscalYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalHalfYearLabel
		dataType: string
		lineageTag: 151e3189-a7bb-4a78-a83d-30f505fd2f1d
		summarizeBy: none
		sourceColumn: FiscalHalfYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterLabel
		dataType: string
		lineageTag: e29c8a9f-1428-47cd-b111-71f1694c2305
		summarizeBy: none
		sourceColumn: FiscalQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FiscalMonthLabel
		dataType: string
		lineageTag: 402991eb-cb8a-4edb-bda2-9d2c3499c123
		summarizeBy: none
		sourceColumn: FiscalMonthLabel

		annotation SummarizationSetBy = Automatic

	column IsWorkDay
		dataType: string
		lineageTag: 3378e7a2-4a1f-4589-8235-9ab1e6642723
		summarizeBy: none
		sourceColumn: IsWorkDay

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: 159e1a46-90dc-444f-9956-942d638bb410
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column EuropeSeason
		dataType: string
		lineageTag: 8fa3f7ce-95de-4a2b-8774-d3ec89126928
		summarizeBy: none
		sourceColumn: EuropeSeason

		annotation SummarizationSetBy = Automatic

	column NorthAmericaSeason
		dataType: string
		lineageTag: 4edd57a1-4096-43e5-b0b2-13134631e5b7
		summarizeBy: none
		sourceColumn: NorthAmericaSeason

		annotation SummarizationSetBy = Automatic

	column AsiaSeason
		dataType: string
		lineageTag: 49bcc8c1-8d5a-4491-9924-2c938f5f1558
		summarizeBy: none
		sourceColumn: AsiaSeason

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 5f41664d-edfa-4c76-a92a-188228f76e87
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column CalendarDayOfWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 7ec828f5-e73e-4db7-998f-2bd46c5abbbc
		summarizeBy: none
		sourceColumn: CalendarDayOfWeekNumber

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jzivaljevic\OneDrive - ENDAVA\Desktop\KrisPOCversioning\data\DimDate.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DateKey", type date}, {"CalendarYear", Int64.Type}, {"CalendarYearLabel", type text}, {"CalendarHalfYearLabel", type text}, {"CalendarQuarterLabel", type text}, {"CalendarMonthLabel", type text}, {"CalendarWeekLabel", type text}, {"CalendarDayOfWeekLabel", type text}, {"FiscalYear", Int64.Type}, {"FiscalYearLabel", type text}, {"FiscalHalfYearLabel", type text}, {"FiscalQuarterLabel", type text}, {"FiscalMonthLabel", type text}, {"IsWorkDay", type text}, {"IsHoliday", type text}, {"EuropeSeason", type text}, {"NorthAmericaSeason", type text}, {"AsiaSeason", type text}, {"MonthNumber", Int64.Type}, {"CalendarDayOfWeekNumber", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

