table FactSales
	lineageTag: 4f7e1c18-56bf-4681-89cb-11b72af39268

	column SalesKey
		dataType: int64
		formatString: 0
		lineageTag: 1db75582-0ac5-4394-af76-d4387ad369be
		summarizeBy: count
		sourceColumn: SalesKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd287ca1-e775-4857-9bd9-51515042821a
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channelKey
		dataType: int64
		formatString: 0
		lineageTag: 488f0bd3-2677-48dc-9c64-7b487a60b771
		summarizeBy: count
		sourceColumn: channelKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 94c6e184-ee3b-4737-98ae-b4758fec9a28
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 931d6ce7-43de-4140-ac69-a68f7e324337
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 4ebc6f44-c88c-4be5-af4c-98ba1d20d72a
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: e449d266-5f29-4d86-8734-d4b814cf7eb0
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: b7fe21e6-2ac0-468b-beaf-1bd5b122dacd
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPrice
		dataType: double
		lineageTag: 0b8ae158-4ad3-4da2-96b5-1baa12bb0b25
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesQuantity
		dataType: int64
		formatString: 0
		lineageTag: 4077322d-70bc-476a-a265-0d807c10c0a5
		summarizeBy: sum
		sourceColumn: SalesQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 452e67ed-57f7-4bd6-b06c-8ae5dd335199
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnAmount
		dataType: double
		lineageTag: 3a6e43ce-475a-4737-9a16-a3c5fe58c897
		summarizeBy: sum
		sourceColumn: ReturnAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountQuantity
		dataType: int64
		formatString: 0
		lineageTag: db988dc5-c12f-4b3f-b19a-1b9e0ae6f5b1
		summarizeBy: sum
		sourceColumn: DiscountQuantity

		annotation SummarizationSetBy = Automatic

	column DiscountAmount
		dataType: double
		lineageTag: 633a10f2-44df-43cc-bb51-d9ea76f31275
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalCost
		dataType: double
		lineageTag: 4dcfbcfb-eba8-4316-b912-bd0bd994afa6
		summarizeBy: sum
		sourceColumn: TotalCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		lineageTag: 1dacb576-d3f0-4a9b-8097-2683e7822fa8
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactSales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jzivaljevic\OneDrive - ENDAVA\Desktop\KrisPOCversioning\data\FactSales.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesKey", Int64.Type}, {"DateKey", type date}, {"channelKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"PromotionKey", Int64.Type}, {"CurrencyKey", Int64.Type}, {"UnitCost", type number}, {"UnitPrice", type number}, {"SalesQuantity", Int64.Type}, {"ReturnQuantity", Int64.Type}, {"ReturnAmount", type number}, {"DiscountQuantity", Int64.Type}, {"DiscountAmount", type number}, {"TotalCost", type number}, {"SalesAmount", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

